'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=s=>{try{const u=new URL(s);return /^https?:$/.test(u.protocol)&&!u.username&&!u.password?esc(u.href):'#';}catch{return '#';}};
const fmt=d=>d?new Date(d).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'日期未知';
const day=d=>new Date(d).toLocaleDateString('en-CA',{timeZone:'Asia/Shanghai'});
const KEY='photo-signal-workspace-v1';
let data,brief,baseline={},localBaseline={},page='overview',shown=30,measurements={},draftTopic='',draftInsight=null;
let filter={q:'',platform:'',topic:'',brand:'',sentiment:'',days:'30',sort:'latest'}, trendPlatform='', state={observations:[],records:[],capabilities:{}};
const plans={
  '胶片与风格':{title:'把流行风格变成可复现配方',hypothesis:'同一套配方在日光、室内和夜景中都能保持目标肤色与层次。',steps:['挑选 3 个有原图或参数的效果样本，记录光源、色温、曝光和滤镜。','在同一设备拍 Kapi / 对照应用各 3 张，关闭不同的自动美颜，保存原片与效果图。','随机盲评肤色、层次和风格相似度；记录参数与失败场景。'],gate:'至少 3 场景 × 3 次，盲评偏好与暗部/高光损失一起判断。'},
  '拍摄与构图':{title:'验证拍摄辅助是否让用户拍得更好',hypothesis:'构图或曝光提示能提高新手的成片选择率，而不显著增加拍摄时间。',steps:['选人像、静物、逆光三个场景，每轮只改变构图提示或曝光补偿一个因素。','同一机位交替拍摄引导开/关各 3 次，记录拍摄耗时和失败原因。','隐藏应用与模式信息，让至少 3 人评选构图与主体表达。'],gate:'记录选择率、耗时中位数、失败次数；样本不足时保持待验证。'},
  'AI 与计算摄影':{title:'让研究结果通过移动端约束',hypothesis:'选定模型能在目标 Android / iOS 设备上改善效果且满足延迟与内存预算。',steps:['从工程或论文原文核验许可证、模型大小、输入尺寸及可复现代码。','用同一组授权图片运行基线与候选模型；记录设备、版本、时延、内存及失败图。','比较真实图与困难图；不以论文分数替代移动端体验。'],gate:'至少两档目标设备，冷/热启动与 20 张以上样图；预算由业务先定义。'},
  '画质与评测':{title:'建立预览 → 成片的画质回归集',hypothesis:'调整后主体细节与曝光更稳定，没有通过过度锐化或去噪掩盖损失。',steps:['固定光线、机位、焦段、输出尺寸，拍日光人像、低光与细密纹理各 3 次。','保存原图、处理图、设备与版本；在评测室等尺寸比较高光/暗部比例、细节响应。','将指标与 100% 裁切盲评、原有端内诊断一起记录；噪点不能当细节提升。'],gate:'至少 3 场景 × 3 次；关键场景无退化，保留失败样本与复现条件。'},
  '实况与创作':{title:'从热门玩法到可完成的创作流程',hypothesis:'用户能更少步骤完成效果复现，导出后照片/视频/实况仍兼容目标平台。',steps:['从来源中选一种明确玩法，记录示例步骤、比例、帧率和输出格式。','同一素材在 Kapi 与对照应用中完成 3 次，记录步骤、时间与质量损失。','在 Android / iOS 相册和目标分享平台实际打开，确认方向、声音与实况标识。'],gate:'流程完成率、操作步数、导出耗时与跨平台可打开性均有证据。'},
  '用户体验与付费':{title:'把评论中的抱怨变成可验收问题',hypothesis:'重复抱怨对应可复现的具体路径，而非版本差异或样本偏差。',steps:['按版本、平台、地区合并相同问题，保留评论链接与日期。','在对应版本复现，并记录期望、实际结果、影响范围。','先解决能复现的高影响问题，再用新一批评论和行为数据看变化。'],gate:'至少 2 个独立样本或 1 条可靠复现；样本舆情不能替代全量指标。'}
};
function notice(text,warn=false){$('#notice').textContent=text;$('#notice').classList.toggle('warn',warn);}
function persist(next){localStorage.setItem(KEY,JSON.stringify(next));state=next;}
try{const old=JSON.parse(localStorage.getItem(KEY));if(old)state=validateWorkspace(old);}catch{notice('无法读取本地记录；请检查浏览器存储权限。',true);}
function validateWorkspace(v){
  if(!v||!Array.isArray(v.observations)||!Array.isArray(v.records)||v.observations.length>2000||v.records.length>2000)throw Error('备份格式不正确或超过 2000 条');
  for(const o of v.observations)if(typeof o.id!=='string'||typeof o.title!=='string'||!Array.isArray(o.topics)||url(o.url)==='#')throw Error('观察记录格式无效');
  for(const r of v.records)if(typeof r.id!=='string'||typeof r.title!=='string'||typeof r.result!=='string')throw Error('实践记录格式无效');
  return {observations:v.observations,records:v.records,capabilities:v.capabilities&&typeof v.capabilities==='object'?v.capabilities:{}};
}
const all=()=>[...data.items,...state.observations];
const timestamp=i=>i.published_at||i.first_seen;
function recent(items,days=30){const start=Date.now()-days*864e5;return items.filter(i=>new Date(timestamp(i)).getTime()>=start);}
function selectItems(){
  let rows=all().filter(i=>(!filter.platform||i.platform===filter.platform)&&(!filter.topic||i.topics.includes(filter.topic))&&(!filter.brand||i.brand===filter.brand)&&(!filter.sentiment||i.sentiment===filter.sentiment)&&(!filter.q||(i.title+' '+i.summary+' '+i.topics.join(' ')).toLowerCase().includes(filter.q.toLowerCase())));
  if(filter.days!=='all')rows=recent(rows,Number(filter.days));
  if(filter.sort==='growth')rows=rows.filter(i=>i.metric_name==='stars'&&i.metric_delta!==null);
  return rows.sort((a,b)=>filter.sort==='growth'?(b.metric_delta??-Infinity)-(a.metric_delta??-Infinity):new Date(timestamp(b))-new Date(timestamp(a)));
}
function option(values,selected){return values.map(v=>`<option value="${esc(v)}" ${v===selected?'selected':''}>${esc(v)}</option>`).join('');}
function card(i){return `<article class="signal"><div class="meta"><span>${esc(i.platform)}${i.brand?' / '+esc(i.brand):''}</span><span>·</span><span>${i.published_at?fmt(i.published_at):'首见 '+fmt(i.first_seen)}</span></div><h3><a href="${url(i.url)}" target="_blank" rel="noopener noreferrer">${esc(i.title)} ↗</a></h3>${i.summary?`<p>${esc(i.summary)}</p>`:''}<div class="meta">${i.kind==='manual'?'人工观察 · 原帖未自动核验':i.kind==='github'?'最近推送时间，不是仓库创建时间':i.published_at?'来源发布时间':'原帖日期未知，不能据此判为新发布'}${i.metric_name==='stars'?` · ★ ${i.metric}${i.metric_delta!==null?' · 观察期 '+(i.metric_delta>0?'+':'')+i.metric_delta:' · 待积累增量'}`:''}</div><div class="tags">${i.topics.slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}${i.sentiment!=='未判定'?`<span class="tag ${i.sentiment==='负向'?'negative':'positive'}" title="${esc(i.sentiment_basis)}">${esc(i.sentiment)} · ${esc(i.metric)}/5</span>`:''}</div></article>`;}
function heading(kicker,title,description){return `<div class="page-head"><div class="kicker">${kicker}</div><h1>${title}</h1><p>${description}</p></div>`;}
function topicCounts(items){return data.topics.map(t=>({topic:t,count:items.filter(i=>i.topics.includes(t)).length})).sort((a,b)=>b.count-a.count);}
function bars(items){
  const days=Array.from({length:14},(_,i)=>day(Date.now()-(13-i)*864e5));
  const first=all().length?day(Math.min(...all().map(i=>new Date(i.first_seen).getTime()))):day(Date.now());
  const counts=days.map(d=>items.filter(i=>day(i.first_seen)===d).length),max=Math.max(...counts,1);
  return `<div class="chart" role="img" aria-label="14 天首次发现条数；监控开始前为空白，不代表零讨论">${days.map((d,i)=>`<div class="bar-cell" title="${d}: ${d<first?'尚未监控':counts[i]+' 条首次发现'}"><span style="font-size:9px">${counts[i]||''}</span><div class="bar" style="height:${counts[i]/max*105}px"></div><span class="bar-label">${d.slice(5)}${d<first?' ·':''}</span></div>`).join('')}</div><p class="chart-caption">按首次发现去重计数（北京时间）。监控始于 ${first}，此前未采集；首轮入库不能解读为突然爆发。</p>`;
}
function overview(){
  const rows=recent(all(),7),ratings=rows.filter(i=>i.metric_name==='rating'),negative=ratings.filter(i=>i.sentiment==='负向');
  const good=data.sources.filter(s=>s.status==='ok').length,counts=topicCounts(rows),max=Math.max(...counts.map(x=>x.count),1);
  return `<section class="hero"><div><div class="kicker">A WIDER VIEW. A CLEARER DIRECTION.</div><h1>看见摄影的变化，<br>找到下一次<em>突破。</em></h1><p>聚合真实动态，听见用户声音。把散落的灵感，变成有来源、有对照、能复现的产品实践。</p><div class="actions"><a href="#signals" class="button primary">探索最新信号 ↗</a><a href="#lab" class="button">开始一次评测</a></div></div><div class="hero-aside"><span class="kicker">THIS WEEK'S FIELD OF VIEW</span><div class="big">${rows.length}</div><small>近 7 天条目<br>已知发布时间优先，未知使用首见时间</small></div></section>
  <div class="stat-grid"><div class="stat"><small>自动来源健康</small><strong>${good}<span style="font-size:17px"> / ${data.sources.length}</span></strong><small>含 3 个待接通社交平台</small></div><div class="stat"><small>近 7 天评论样本</small><strong>${ratings.length}</strong><small>仅 App Store 中国区样本</small></div><div class="stat"><small>负向评论样本</small><strong>${negative.length}</strong><small>${ratings.length?Math.round(negative.length/ratings.length*100)+'% 的本期评分样本':'暂无本期评分样本'}，非市场占比</small></div><div class="stat"><small>已沉淀的实践</small><strong>${state.records.length}</strong><small>保存在当前浏览器</small></div></div>
  <div class="two-col"><section class="panel"><h2>信号的时间轨迹</h2>${bars(all())}</section><section class="panel"><h2>本周关注什么</h2>${counts.map(c=>`<div class="topic-row"><div><a href="#signals" data-topic="${esc(c.topic)}">${esc(c.topic)}</a><span>${c.count}</span></div><div class="track"><span style="width:${c.count/max*100}%"></span></div></div>`).join('')}<p class="method">按关键词分类，可多标签；条数表示已采集样本量。</p></section></div>
  <div class="section-title"><h2>值得打开的最新信号</h2><a href="#signals">全部资料 ↗</a></div><div class="signal-grid">${[...rows].sort((a,b)=>new Date(timestamp(b))-new Date(timestamp(a))).slice(0,6).map(card).join('')||'<div class="empty">本期尚无条目，查看来源状态或延长时间范围。</div>'}</div>
  <div class="section-title"><h2>按平台观察变化</h2><select id="trend-platform" aria-label="趋势平台"><option value="">全部平台</option>${option([...new Set(data.sources.map(s=>s.platform))],trendPlatform)}</select></div><div class="panel" id="platform-trend"></div>
  <div class="section-title"><h2>评论情绪的变化</h2><span>按评论发布时间 · 近 7 天</span></div><div class="panel table-wrap"><table><thead><tr><th>日期</th><th>评分样本</th><th>正向</th><th>中性</th><th>负向</th><th>负向占样本</th></tr></thead><tbody>${Array.from({length:7},(_,n)=>{const d=day(Date.now()-(6-n)*864e5),rs=all().filter(i=>i.metric_name==='rating'&&i.published_at&&day(i.published_at)===d),neg=rs.filter(i=>i.sentiment==='负向').length;return `<tr><td>${d}</td><td>${rs.length||'无样本'}</td><td>${rs.filter(i=>i.sentiment==='正向').length}</td><td>${rs.filter(i=>i.sentiment==='中性').length}</td><td>${neg}</td><td>${rs.length?Math.round(neg/rs.length*100)+'%':'—'}</td></tr>`;}).join('')}</tbody></table><p class="method">来自当前已归档的商店评论，不是当天全量。新抓到的历史评论会回填其发布日期，接口分页造成覆盖偏差。</p></div>
  <div class="banner">小红书、X、抖音尚未接通自动采集。当前趋势与舆情仅覆盖已接通来源及人工观察，不代表全网热度。<a href="#sources">查看覆盖详情 ↗</a></div>`;
}
function signals(){return `${heading('02 / SIGNAL LIBRARY','信号资料库','按平台、主题和时间找到线索。每条都保留来源，未知日期单独标识。')}<div class="actions"><button id="add-observation" class="primary">＋ 录入观察</button><button id="export-signals">导出筛选结果</button></div><div class="filters"><input id="query" aria-label="搜索关键词" placeholder="搜索摄影、胶片、构图、画质…" value="${esc(filter.q)}"><select data-filter="platform" aria-label="平台"><option value="">全部平台</option>${option([...new Set([...data.sources.map(s=>s.platform),...all().map(i=>i.platform)])],filter.platform)}</select><select data-filter="topic" aria-label="主题"><option value="">全部主题</option>${option(data.topics,filter.topic)}</select><select data-filter="brand" aria-label="品牌"><option value="">全部品牌</option>${option(['Kapi','Dazz','ProCCD'],filter.brand)}</select><select data-filter="sentiment" aria-label="情绪"><option value="">全部情绪</option>${option(['正向','中性','负向','未判定'],filter.sentiment)}</select><select data-filter="days" aria-label="时间范围">${[['7','近 7 天'],['30','近 30 天'],['all','全部历史']].map(([v,l])=>`<option value="${v}" ${v===filter.days?'selected':''}>${l}</option>`).join('')}</select><select data-filter="sort" aria-label="排序"><option value="latest">最新动态</option><option value="growth" ${filter.sort==='growth'?'selected':''}>已观测星标增量</option></select></div><p id="result-count" class="muted"></p><div id="signal-list" class="signal-grid"></div><button id="more" class="load-more">再看 30 条</button>`;}
function fillSignals(){const rows=selectItems();$('#result-count').textContent=`${rows.length} 条匹配 · 情绪仅来自商店评分；未判定不等于中性。`;$('#signal-list').innerHTML=rows.slice(0,shown).map(card).join('')||'<div class="empty">当前筛选没有条目。可扩大时间范围，或到「来源与覆盖」检查是否接通。</div>';$('#more').classList.toggle('hidden',shown>=rows.length);}
function capabilities(){return {...baseline.capabilities,...localBaseline.capabilities,...state.capabilities};}
function decisionBrief(){
  brief=PhotoInsights.build(all());
  return `<div class="section-title"><h2>本期决策简报</h2><button id="export-brief">导出简报与证据</button></div><p class="method">截至 ${fmt(brief.as_of)}，按近 30 天评论发布时间归并；同一品牌至少 2 条低分评论命中同一关键词组才形成候选。词语命中可能误判，需展开摘录确认；链接进入商店评论列表，可按标题与日期查找原文。评论数不等于独立用户数。优先呈现 Kapi，组内按样本量排序。</p>
  <div class="signal-grid">${brief.candidates.slice(0,6).map(c=>`<article class="signal gap"><div class="meta">${c.brand==='Kapi'?'本品待核验':'竞品观察'} · ${c.count} 条命中 / ${c.total} 条评分样本</div><h3>${esc(c.title)}</h3><p>${esc(c.hypothesis)}</p><p><strong>下一步：</strong>${esc(c.action)}</p><details><summary>核对 ${c.count} 条原文</summary>${c.evidence.map(i=>`<p><a href="${url(i.url)}" target="_blank" rel="noopener noreferrer">${esc(i.title)} ↗</a><br>${fmt(i.published_at)} · ${i.rating}/5<br>${esc(i.summary)}</p>`).join('')}</details><button class="primary" data-insight="${esc(c.id)}">带入假设与证据</button></article>`).join('')||'<div class="empty">当前没有达到 2 条匹配样本的候选；不代表没有问题。可查看单条评论或补充实测。</div>'}</div>
  <div class="panel table-wrap" style="margin-top:18px"><table><thead><tr><th>品牌</th><th>近 7 天负向 / 评分</th><th>前 7 天负向 / 评分</th><th>解读边界</th></tr></thead><tbody>${brief.brands.map(b=>`<tr><td>${esc(b.brand)}</td><td>${b.week.negative} / ${b.week.count}</td><td>${b.previous.negative} / ${b.previous.count}</td><td>${b.comparable?'可对照已采集样本，不能推断全量舆情变化':'至少一段不足 10 条评分，暂不比较比例变化'}</td></tr>`).join('')}</tbody></table><p class="method">中国区 App Store 最近页归档，区间为连续 7 × 24 小时；排除未知、未来和无效评分。候选可重叠，不能相加成总投诉量。导出保留全部候选和原文链接。</p></div>`;
}
function gaps(){
  const rows=recent(all(),30),counts=topicCounts(rows),caps=capabilities();
  const ranked=counts.map(c=>({...c,items:rows.filter(i=>i.topics.includes(c.topic))}));
  return `${heading('03 / DECISION NOTEBOOK','从趋势，到可以验证的方向','先分清能力存在、用户体验与效果质量，再决定做什么。以下方向来自已采集线索，尚不是确认的产品缺陷。')}<div class="banner">基线：${esc(localBaseline.scope||baseline.scope)}<br>核验日期 ${esc(localBaseline.checked_at||baseline.checked_at)}。<a href="${url(baseline.evidence)}" target="_blank" rel="noopener noreferrer">公开依据 ↗</a></div>
  ${decisionBrief()}
  <div class="section-title"><h2>竞品声音对照</h2><span>近 30 天 · 中国区评论样本</span></div><div class="panel table-wrap"><table><thead><tr><th>产品</th><th>公开能力观察</th><th>评论 / 负向</th><th>下一步实测</th></tr></thead><tbody>${(baseline.competitors||[]).map(c=>{const stats=brief.brands.find(b=>b.brand===c.name);return `<tr><td><a href="${url(c.url)}" target="_blank" rel="noopener noreferrer"><strong>${esc(c.name)} ↗</strong></a></td><td>${esc(c.observation)}</td><td>${stats?.count||0} / ${stats?.negative||0}</td><td>${esc(c.next)}</td></tr>`;}).join('')}</tbody></table><p class="method">商店描述只能证明功能宣传，无法证明效果领先。评论量受接口分页和地区影响，不能据此排名产品好坏。</p></div>
  <div class="section-title"><h2>本期可推进的实践</h2><span>按匹配线索数量排序 · 多来源交叉核验</span></div><div class="signal-grid">${ranked.map((c,index)=>{const plan=plans[c.topic],platforms=new Set(c.items.map(i=>i.platform));return `<article class="signal gap"><div class="rank">${String(index+1).padStart(2,'0')}</div><div class="meta">${c.count} 条线索 · ${platforms.size} 个平台 · ${platforms.size>1?'可交叉核验':'证据仍薄弱'}</div><h3>${esc(plan.title)}</h3><p><strong>当前基线：</strong>${esc(caps[c.topic]||'尚未核验')}</p><p><strong>要验证：</strong>${esc(plan.hypothesis)}</p><ol>${plan.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p><strong>验收：</strong>${esc(plan.gate)}</p><details><summary>打开本期证据（${c.count}）</summary>${c.items.slice(0,5).map(i=>`<p><a target="_blank" rel="noopener noreferrer" href="${url(i.url)}">${esc(i.title)} ↗</a></p>`).join('')||'<p>尚无线索，暂不据此排期。</p>'}</details><button class="primary" data-practice="${esc(c.topic)}">带入评测记录</button></article>`;}).join('')}</div>
  <details><summary>更新我的能力基线（保存在此浏览器）</summary><form id="baseline-form">${data.topics.map(t=>`<label>${esc(t)}<textarea name="${esc(t)}" maxlength="1000">${esc(caps[t]||'')}</textarea></label>`).join('')}<button class="primary">保存基线</button></form></details>`;
}
function lab(){return `${heading('04 / PRACTICE LAB','让每一次尝试，留下证据。','Android / iOS 的拍摄实践与效果评测放在一起：固定条件、对比、记录，再决定是否推进。')}<div class="panel"><h2>两张图，同一把尺</h2><p class="method">图片只在浏览器分析，不上传。长边统一至 512 像素；不同画幅或不同构图应重新取相同区域。支持 JPEG / PNG / WebP，单图 15 MB。</p><div class="upload-grid">${['A','B'].map(k=>`<div class="photo-slot"><label>样本 ${k} · ${k==='A'?'基线 / 原片':'候选 / 效果图'}<input type="file" data-photo="${k}" accept="image/jpeg,image/png,image/webp"></label><canvas id="canvas-${k}" width="1" height="1" class="hidden"></canvas><p id="photo-${k}" class="muted">等待选择图片</p></div>`).join('')}</div><div id="metric-output"></div><p class="banner">细节响应会同时受到纹理、噪点与锐化影响；曝光阈值是可调诊断参数。胶片颗粒、低调和高调风格可能是有意设计，指标不代表审美优劣。</p></div>
  <div class="section-title"><h2>记录一轮实践</h2><span>照片不进入记录；仅保存指标与观察</span></div><form id="record-form" class="panel"><div class="form-grid"><label>实践主题<select name="topic">${option(data.topics,draftTopic)}</select></label><label>标题<input name="title" required maxlength="160" value="${esc(plans[draftTopic]?.title||'')}"></label><label>端与设备<input name="device" required placeholder="Android / iOS、机型、系统版本"></label><label>应用 / 版本 / 对照<input name="version" required placeholder="Kapi 版本、对照应用版本"></label><label>场景与固定参数<input name="scene" required placeholder="光线、机位、焦段、ISO、快门、滤镜、输出尺寸"></label><label>重复次数<input name="repeats" type="number" min="1" max="10000" value="3" required></label><label class="wide">假设<textarea name="hypothesis" required>${esc(plans[draftTopic]?.hypothesis||'')}</textarea></label><label>盲评结论<select name="verdict"><option>待验证</option><option>候选更好</option><option>无明显差异</option><option>基线更好</option><option>存在退化</option></select></label><label>评审人数<input name="reviewers" type="number" min="0" max="10000" value="0" required></label><label class="wide">结果与失败场景<textarea name="result" required maxlength="5000" placeholder="写实际观察、指标变化和复现步骤；不要把计划写成已完成。"></textarea></label><label class="wide">来源链接 / 本地证据位置<textarea name="evidence" maxlength="3000" placeholder="原帖 URL、样张文件位置、日志标识（仅本机保存）"></textarea></label></div><button class="primary">保存实践与当前指标</button></form>
  <div class="section-title"><h2>实践档案 <span id="record-count"></span></h2><div class="actions"><button id="backup">导出备份</button><label class="button" style="margin:0">合并导入备份<input id="restore" type="file" accept="application/json" class="hidden"></label></div></div><div id="records"></div>`;}
function renderRecords(){
  $('#record-count').textContent=state.records.length;
  $('#records').innerHTML=state.records.map(r=>`<article class="record"><div class="meta muted">${esc(r.topic)} · ${fmt(r.created_at)} · ${esc(r.verdict)}</div><h3>${esc(r.title)}</h3><p>${esc(r.result)}</p><details><summary>条件与证据</summary><p>设备：${esc(r.device)}<br>版本：${esc(r.version)}<br>场景：${esc(r.scene)}<br>重复 ${esc(r.repeats)} 次 · 评审 ${esc(r.reviewers)} 人<br>假设：${esc(r.hypothesis)}</p><p>${esc(r.evidence)}</p><pre style="overflow:auto">${esc(JSON.stringify(r.measurements||{},null,2))}</pre></details><button class="delete" data-delete="${esc(r.id)}">移除此记录</button></article>`).join('')||'<div class="empty">还没有实践记录。完成一次真实对照后，把成功和失败都留下。</div>';
}
function sources(){return `${heading('05 / COVERAGE & SOURCES','知道看见了什么，也知道漏了什么。','每个来源独立记录状态和最后成功时间。失败保留旧数据，刷新不意味着所有来源都成功。')}<div class="banner">免费模式每 2 小时计划采集，GitHub Actions 可能延迟。本地服务器运行期间也会每 2 小时采集，支持立即刷新。页面自动检查快照每 5 分钟一次。</div><div class="panel">${data.sources.map(s=>`<div class="source-row"><div><h3>${esc(s.name)}</h3><p>${esc(s.platform)} · ${s.count} 条本次有效记录</p><p>最后成功 ${fmt(s.last_success)}</p></div><span class="${esc(s.status)}">${({ok:'已接通',error:'采集失败',empty:'本轮无条目',pending:'待接通'})[s.status]||esc(s.status)}</span><div><p>${esc(s.note)}</p><p>${esc(s.detail)} ${s.checked_at?'最近尝试 '+fmt(s.checked_at):''}</p>${s.search_url?`<a class="button" href="${url(s.search_url)}" target="_blank" rel="noopener noreferrer">打开平台搜索 ↗</a>`:''}</div></div>`).join('')}</div>
  <div class="section-title"><h2>关键词与接入方式</h2></div><div class="panel"><div class="tags">${data.keywords.map(k=>`<span class="tag">${esc(k)}</span> `).join('')}</div><p>已有授权的 RSS / Atom 来源可配置在本地 <code>data/local-sources.json</code>，采集后进入对应平台。含登录信息的来源只在本机使用。网站可直接录入社交平台观察，支持备份。</p><p><a href="https://github.com/fanpeihua/photo-signal#来源接入" target="_blank" rel="noopener noreferrer">配置说明 ↗</a></p><div class="actions"><button id="add-observation" class="primary">录入一条观察</button><a class="button" href="https://github.com/fanpeihua/photo-signal/actions/workflows/collect.yml" target="_blank" rel="noopener noreferrer">查看远端采集任务 ↗</a></div></div>`;}
function render(){
  page=location.hash.slice(1)||'overview';if(!['overview','signals','gaps','lab','sources'].includes(page))page='overview';
  document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+page));
  $('#app').innerHTML=({overview,signals,gaps,lab,sources})[page]();
  if(page==='overview'){const draw=()=>$('#platform-trend').innerHTML=bars(all().filter(i=>!trendPlatform||i.platform===trendPlatform));draw();$('#trend-platform').onchange=e=>{trendPlatform=e.target.value;draw();};}
  if(page==='signals'){fillSignals();$('#query').oninput=e=>{filter.q=e.target.value;shown=30;fillSignals();};document.querySelectorAll('[data-filter]').forEach(s=>s.onchange=()=>{filter[s.dataset.filter]=s.value;shown=30;fillSignals();});$('#more').onclick=()=>{shown+=30;fillSignals();};$('#export-signals').onclick=()=>download('photo-signals.json',selectItems());}
  if(page==='lab'){measurements={};renderRecords();$('#metric-output').insertAdjacentHTML('beforebegin','<div class="form-grid"><label>暗部阈值<input id="dark-threshold" type="number" min="0" max="254" value="5"></label><label>高光阈值<input id="bright-threshold" type="number" min="1" max="255" value="250"></label></div>');document.querySelectorAll('[data-photo]').forEach(i=>i.onchange=()=>analyze(i));for(const name of ['dark','bright'])$('#'+name+'-threshold').onchange=()=>{for(const i of document.querySelectorAll('[data-photo]'))if(i.files[0])analyze(i);};$('#record-form').onsubmit=saveRecord;$('#backup').onclick=()=>download('photo-signal-workspace.json',state);$('#restore').onchange=restore;}
  if(page==='lab'&&draftInsight){const f=$('#record-form').elements;f.title.value=draftInsight.title;f.hypothesis.value=draftInsight.hypothesis+'\n'+draftInsight.action;f.evidence.value=draftInsight.evidence.map(i=>i.title+' · '+i.published_at+'\n'+i.url).join('\n\n');}
  if($('#add-observation'))$('#add-observation').onclick=()=>$('#import-dialog').showModal();
  if($('#export-brief'))$('#export-brief').onclick=()=>download('photo-signal-brief.json',{...brief,snapshot_at:data.generated_at,scope:'中国区 App Store 最近页样本；关键词候选不代表确认缺陷或全网趋势。',sources:data.sources.map(s=>({name:s.name,status:s.status,last_success:s.last_success}))});
  if($('#baseline-form'))$('#baseline-form').onsubmit=e=>{e.preventDefault();try{persist({...state,capabilities:Object.fromEntries(new FormData(e.target))});notice('能力基线已保存到当前浏览器。');}catch{notice('保存失败，请导出后检查浏览器存储空间。',true);}};
}
document.addEventListener('click',e=>{const topic=e.target.closest('[data-topic]'),practice=e.target.closest('[data-practice]'),insight=e.target.closest('[data-insight]'),del=e.target.closest('[data-delete]');if(topic){filter.topic=topic.dataset.topic;filter.days='30';if(page==='signals')render();}if(practice){draftTopic=practice.dataset.practice;draftInsight=null;location.hash='lab';}if(insight){draftInsight=brief.candidates.find(c=>c.id===insight.dataset.insight);if(draftInsight){draftTopic=draftInsight.topic;location.hash='lab';}}if(del){try{persist({...state,records:state.records.filter(r=>r.id!==del.dataset.delete)});renderRecords();}catch{notice('删除未保存，存储不可用。',true);}}});
function download(name,value){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function restore(e){try{const file=e.target.files[0];if(!file)return;if(file.size>5e6)throw Error('备份超过 5 MB');const imported=validateWorkspace(JSON.parse(await file.text()));const merge=(a,b)=>[...new Map([...b,...a].map(r=>[r.id,r])).values()];persist({observations:merge(state.observations,imported.observations),records:merge(state.records,imported.records),capabilities:{...imported.capabilities,...state.capabilities}});renderRecords();notice('备份已合并，同 ID 保留当前记录。');}catch(err){notice('导入失败：'+err.message,true);}}
function saveRecord(e){e.preventDefault();const r={...Object.fromEntries(new FormData(e.target)),id:crypto.randomUUID(),created_at:new Date().toISOString(),measurements:JSON.parse(JSON.stringify(measurements))};try{persist({...state,records:[r,...state.records]});renderRecords();notice('实践已保存，可导出备份。');}catch{notice('存储失败，当前填写内容已保留，请先复制或导出。',true);}}
async function analyze(input){const k=input.dataset.photo,f=input.files[0];if(!f)return;delete measurements[k];const canvas=$('#canvas-'+k);canvas.classList.add('hidden');try{
  if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>15e6)throw Error('请选择不超过 15 MB 的 JPEG / PNG / WebP');
  const bmp=await createImageBitmap(f);const w=bmp.width,h=bmp.height;
  if(w*h>60000000||w<3||h<3){bmp.close();throw Error('支持 3×3 至 6000 万像素图片');}
  const scale=Math.min(1,512/Math.max(w,h));canvas.width=Math.max(3,Math.round(w*scale));canvas.height=Math.max(3,Math.round(h*scale));const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bmp,0,0,canvas.width,canvas.height);bmp.close();
  measurements[k]={file:f.name,width:w,height:h,analysis_width:canvas.width,analysis_height:canvas.height,...PhotoMetrics.measure(ctx.getImageData(0,0,canvas.width,canvas.height).data,canvas.width,canvas.height,Number($('#dark-threshold').value),Number($('#bright-threshold').value))};canvas.classList.remove('hidden');$('#photo-'+k).textContent=f.name+' · '+w+' × '+h;
 }catch(err){$('#photo-'+k).textContent=err.message;}showMetrics();}
function showMetrics(){const names={luma:'平均亮度（0–255）',dark:'近黑像素（按所设阈值，%）',bright:'近白像素（按所设阈值，%）',laplacian:'细节响应（Laplacian 方差）',redBlue:'红蓝均值差（非白平衡误差）'};$('#metric-output').innerHTML=`<div class="table-wrap"><table class="metric-table"><thead><tr><th>指标</th><th>样本 A</th><th>样本 B</th></tr></thead><tbody>${Object.entries(names).map(([k,n])=>`<tr><td>${n}</td>${['A','B'].map(s=>`<td>${measurements[s]?measurements[s][k].toFixed(2):'—'}</td>`).join('')}</tr>`).join('')}</tbody></table></div>${measurements.A&&measurements.B&&Math.abs(measurements.A.width/measurements.A.height-measurements.B.width/measurements.B.height)>.01?'<p class="banner">两张图片画幅不同，先裁成相同区域再比较细节。</p>':''}`;}
$('#close-import').onclick=()=>$('#import-dialog').close();
$('#import-form').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));if(url(v.url)==='#')return notice('请填写有效的 http/https 原文链接。',true);if(v.published_at&&new Date(v.published_at)>new Date())return notice('发布日期不能晚于今天。',true);const txt=(v.title+' '+v.summary).toLowerCase();const topics=data.topics.filter(t=>t.split('与').some(w=>txt.includes(w.toLowerCase())));const o={...v,id:'local-'+crypto.randomUUID(),first_seen:new Date().toISOString(),last_seen:new Date().toISOString(),published_at:v.published_at||null,topics:topics.length?topics:['行业动态'],sentiment:'未判定',brand:'',kind:'manual',metric_delta:null,metric:null,metric_name:''};try{persist({...state,observations:[o,...state.observations]});$('#import-dialog').close();e.target.reset();render();notice('观察已保存到此浏览器；在实践评测室可导出包含观察的完整备份。');}catch{notice('存储失败，表单已保留。',true);}};
async function api(path){const r=await fetch(path,{method:'POST',headers:{'X-Photo-Signal':'1'}});if(!r.ok)throw Error((await r.json()).error||'请求失败');return r.json();}
async function load(redraw=true){const r=await fetch('snapshot.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('数据尚未就绪，请检查采集任务');data=await r.json();if(!Array.isArray(data.items)||!Array.isArray(data.sources))throw Error('数据格式错误');$('#mode').textContent=data.mode==='local'?'本地实时采集':'云端定时采集';const checked=data.sources.filter(s=>s.checked_at).map(s=>new Date(s.checked_at).getTime()),last=checked.length?Math.max(...checked):0;const bad=data.sources.filter(s=>s.status==='error').length;notice(`最近采集尝试 ${last?fmt(last):'尚无'} · ${data.items.length} 条已归档${bad?' · '+bad+' 个来源失败':''}${Date.now()-last>26*3600e3?' · 数据已超过一天未更新，请检查采集任务':''}`,Date.now()-last>26*3600e3||bad>0);if(redraw)render();}
$('#refresh').onclick=async()=>{const b=$('#refresh');b.disabled=true;try{if(data?.mode==='local'){await api('/api/collect');notice('正在采集，完成后更新页面…');for(let i=0;i<90;i++){await new Promise(r=>setTimeout(r,2000));if(!(await api('/api/status')).running)break;}}await load(page!=='lab');}catch(e){notice(e.message,true);}finally{b.disabled=false;}};
$('#today').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'});
window.addEventListener('hashchange',()=>{if(data){render();window.scrollTo(0,0);}});
(async()=>{try{baseline=await(await fetch('baseline.json')).json();await load(false);if(data.mode==='local'){localBaseline=await(await fetch('/api/baseline')).json();}render();setInterval(()=>load(page!=='lab').catch(e=>notice(e.message,true)),300000);}catch(e){notice(e.message,true);$('#app').innerHTML='<div class="empty">暂时无法载入。请刷新重试，或检查远端采集任务。</div>';}})();
